apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: test-git-lfs
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: test-git-lfs
spec:
  output:
    to:
      kind: 'ImageStreamTag'
      name: 'test-git-lfs:latest'
  source:
    git:
      uri: "https://github.com/selrahal/buildconfig-git-lfs.git"
  strategy:
    dockerStrategy:
