apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: test-git-lfs
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: test-git-lfs
spec:
  output:
    to:
      kind: 'ImageStreamTag'
      name: 'test-git-lfs:latest'
  resources:
    limits:
      cpu: 500m
      memory: 250Mi
    requests:
      cpu: 200m
      memory: 128Mi
  source:
    git:
      uri: "https://github.com/sreber/buildconfig-git-lfs.git"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 1
